<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\OfflineRadio\OfflineRadio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Eto.Platform.Windows" Version="2.10.2" />
  </ItemGroup>

</Project>
